#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SpotzDroid.Resource", IsApplication=true)]

namespace SpotzDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int btnAddSpotz = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int btnLogin = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int btnOpenMap = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int btnRefresh = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int btnTakePic = 2131034117;
			
			// aapt resource value: 0x7f05001f
			public const int button1 = 2131034143;
			
			// aapt resource value: 0x7f05000c
			public const int buttonLayout = 2131034124;
			
			// aapt resource value: 0x7f05001c
			public const int imageAvatarSpotzDetail = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int imageMainSpotzDetail = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int imageViewNewPic = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int imageViewSpotz = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int list = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int loadingPanel = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int mainRow = 2131034118;
			
			// aapt resource value: 0x7f05001a
			public const int textAllTags = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int textDescription = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int textDescriptionSpotzDetail = 2131034136;
			
			// aapt resource value: 0x7f050011
			public const int textInputEmail = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int textInputPassword = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int textLayout = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textTitle = 2131034121;
			
			// aapt resource value: 0x7f050017
			public const int textTitleSpotzDetail = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int textUserName = 2131034123;
			
			// aapt resource value: 0x7f05001d
			public const int textUsernameSpotzDetail = 2131034141;
			
			// aapt resource value: 0x7f050012
			public const int textView1 = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int textView2 = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int webViewAddSpotz = 2131034112;
			
			// aapt resource value: 0x7f05001e
			public const int wrapperComments = 2131034142;
			
			// aapt resource value: 0x7f050019
			public const int wrapperTagsSpotzDetail = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int wrapperUsernameAndAvatar = 2131034139;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddSpotzInWebViewLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddSpotzLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_view_data_template = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListSpotzLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SpotzDetailLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TestLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BaseUrl = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int MessageCantFindLocation = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int MessageGpsEnabled = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int MessageNoLocaton = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int MessageNoSpotzBody = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int MessageNoSpotzTitle = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int MessageServerErrorBody = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int MessageServerErrorTitle = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int MessageStatusChanged = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int MessageTurnOnGpsBody = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int MessageTurnOnGpsTitle = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
